### ISSUE TITLE
Region specified by pixels validation test fails due to color error (applies to v2 and v3)

### ISSUE THREAD

**Issue by rafeili** [IIIF/image-validator#101]
We get a Region specified by pixels test fail like so.

V2 validation:
https://iiif.io/api/image/validator/results/?server=https%3A%2F%2Flbiiif.riksarkivet.se&prefix=%2Fv2%2F&identifier=arkis%2130002046_00011&version=2.0&level=-1&id_basic=on&region_pixels=on

Region specified by pixels
Elapsed time (ms): 2946
url: https://lbiiif.riksarkivet.se/v2/arkis!30002046_00011/313,713,74,74/full/0/default.jpg,https://lbiiif.riksarkivet.se/v2/arkis!30002046_00011/113,413,74,74/full/0/default.jpg,https://lbiiif.riksarkivet.se/v2/arkis!30002046_00011/813,313,74,74/full/0/default.jpg,https://lbiiif.riksarkivet.se/v2/arkis!30002046_00011/513,213,74,74/full/0/default.jpg,https://lbiiif.riksarkivet.se/v2/arkis!30002046_00011/713,113,74,74/full/0/default.jpg
got: Expected 0 for color; Got: 1
expected: No error
type: General error
message: Failed to check size due to: Expected 0 for color; Got: 1
warning: false

Other example:
https://iiif.io/api/image/validator/results/?server=https%3A%2F%2Fiiif.bodleian.ox.ac.uk&prefix=%2Fiiif%2Fimage%2F&identifier=daf51525-07c5-43ca-ac63-4e3060694572&version=2.0&level=1&id_basic=on&id_squares=on&info_json=on&id_error_escapedslash=on&id_error_random=on&id_error_unescaped=on&id_escaped=on&region_error_random=on&region_pixels=on&size_ch=on&size_error_random=on&size_percent=on&size_region=on&size_wc=on&rot_error_random=on&quality_error_random=on&format_jpg=on&format_error_random=on&baseurl_redirect=on&cors=on&jsonld=on

Region specified by pixels
Elapsed time (ms): 2071
url: https://iiif.bodleian.ox.ac.uk/iiif/image/daf51525-07c5-43ca-ac63-4e3060694572/713,213,74,74/full/0/default.jpg,https://iiif.bodleian.ox.ac.uk/iiif/image/daf51525-07c5-43ca-ac63-4e3060694572/13,513,74,74/full/0/default.jpg,https://iiif.bodleian.ox.ac.uk/iiif/image/daf51525-07c5-43ca-ac63-4e3060694572/13,513,74,74/full/0/default.jpg,https://iiif.bodleian.ox.ac.uk/iiif/image/daf51525-07c5-43ca-ac63-4e3060694572/513,213,74,74/full/0/default.jpg,https://iiif.bodleian.ox.ac.uk/iiif/image/daf51525-07c5-43ca-ac63-4e3060694572/113,313,74,74/full/0/default.jpg
got: Expected 0 for color; Got: 1
expected: No error
type: General error
message: Failed to check size due to: Expected 0 for color; Got: 1
warning: false

V3 validation:
https://iiif.io/api/image/validator/results/?server=https%3A%2F%2Flbiiif.riksarkivet.se&prefix=%2Fv3%2F&identifier=arkis%2130002046_00011&version=3.0&level=-1&id_basic=on&region_pixels=on

Region specified by pixels
Elapsed time (ms): 3001

url: https://lbiiif.riksarkivet.se/v3/arkis!30002046_00011/713,813,74,74/max/0/default.jpg,https://lbiiif.riksarkivet.se/v3/arkis!30002046_00011/813,713,74,74/max/0/default.jpg,https://lbiiif.riksarkivet.se/v3/arkis!30002046_00011/713,313,74,74/max/0/default.jpg,https://lbiiif.riksarkivet.se/v3/arkis!30002046_00011/813,513,74,74/max/0/default.jpg,https://lbiiif.riksarkivet.se/v3/arkis!30002046_00011/913,813,74,74/max/0/default.jpg
got: Expected 0 for color; Got: 1
expected: No error
type: General error
message: Failed to check size due to: Expected 0 for color; Got: 1
warning: false

As the error is color related, but default is tested as quality value, we would like to ask for more information as to what might be wrong in our implementation. Any other hints / suggestions on how to get rid of this FAIL?

Or might the FAIL be an unfair FAIL?

Maybe the threshold (6) used for comparing color differences (abs(col[i] - truth[i]) < 6) is too strict or too lenient depending on the nature of the images being tested? Can adjusting this threshold potentially improve the test's accuracy?

Please comment. Any suggestions are welcome. Thank you.

**Comment by glenrobson** [comment]
Hi @rafeili, the image server validator tests a known image so that it has the expected dimensions and colours at a particular pixel. You would need to download one of the following images:

 https://iiif.io/api/image/validator/download/

Load it to your image server and re-run the tests.
