### ISSUE TITLE
Validator should be able to validate all HTTPS image servers

### ISSUE THREAD

**Issue by jronallo** [IIIF/image-validator#43]
I'll submit a pull request with a potential quick fix for this, but the validator does not seem to work with at least some HTTPS image servers because it has not context to verify the peer. Adding ssl and an unverified context works around this.

**Comment by glenrobson** [comment]
Is this fixed? I've been updating the dependent libraries and a few urls that didn't work previously do now. Do you have an example that still doesn't work?

**Comment by glenrobson** [comment]
Haven't had any more reports of this but will re-open if we do.
