### ISSUE TITLE
Pillow >= 4.0.0 vs python 2.6 -- pick one

### ISSUE THREAD

**Issue by zimeon** [IIIF/image-validator#50]
We can't use the current major version of Pillow (>= 4.0.0) if we still want to support python 2.6 because Pillow v4 drops support. #49 tied pillow to < 4.0.0 but at some stage we should probably drop python 2.6 support -- but this might cause problems for folks with older RedHat/CentOS VMs.

**Comment by azaroth42** [comment]
Python 2.6 is the version on the iiif.io server:

```
[iiif@ip-172-31-44-83 ~]$ python --version
Python 2.6.6
```

So I think we should pick 2.6 for the moment!

**Comment by zimeon** [comment]
I agree that we should support 2.6 for a bit longer, I think the RHEL problem is bigger than just the iiif.io server as it is widely used in institutions like mine. According to [Red Hat's lifecycle document](https://access.redhat.com/support/policy/updates/errata/), RHEL6 enters its 3rd and final production phase (essentially maintenance only) in May 2017 so hopefully that will mean institutions moving away from RHEL6 and py2.6 this year. 

Propose we revisit the question later in 2017.

**Comment by hugovk** [comment]
It's now later in 2017.

RHEL 6 and CentOS 6 are still on Python 2.6 (with RHEL 5 still on Python 2.4!):

![image](https://user-images.githubusercontent.com/1324225/31775793-3cae17f4-b4f2-11e7-95bf-e601d5101906.png)

https://en.wikipedia.org/wiki/CPython#Enterprise_Linux

Current pip 9 deprecates Python 2.6 support, and pip 10 won't support it (pypa/pip#3955).

**Comment by acdha** [comment]
The EL6 series will never get an upgrade to the core OS but it’s easy to get Python 2.7 or 3.x from RHSCL, IUS Community, etc. See https://access.redhat.com/solutions/92933 for the commercial offering.

Here’s one of the core python developers and a red hat employee on the subject:

http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

I agree with that - unless there are a lot of people willing to pay for supporting old versions, the enterprise IT shops should be on the hook for their policies’ costs.

**Comment by hugovk** [comment]
I think you meant to include this link for the core Python developer:

https://snarky.ca/stop-using-python-2-6/

**Comment by acdha** [comment]
Nick and Brett are both core CPython developers; Nick also works at RH so I figured his post was more compatible with their world view

**Comment by zimeon** [comment]
I agree with the sense of @hugovk and @acdha posts above, it is time to let 2.6 die and focus on python 2.7 + 3.x.

**Comment by hugovk** [comment]
Please see PR #58 and comments welcome. Thank you!

**Comment by zimeon** [comment]
iiif.io servers have Python 3.4 now
