### ISSUE TITLE
3.0 reference implementation showing errors

### ISSUE THREAD

**Issue by nichtich** [IIIF/image-validator#78]
After unsuccessful validation of my own IIIF Image API server I tried to [validate the reference implementation](https://iiif.io/api/image/validator/results/?server=iiif.io&prefix=api%2Fimage%2F3.0%2Fexample%2Freference%2F&identifier=67352ccc-d1b0-11e1-89ae-279075081939&version=3.0&level=1&id_basic=on&id_squares=on&info_json=on&id_error_escapedslash=on&id_error_random=on&id_error_unescaped=on&id_escaped=on&region_error_random=on&region_pixels=on&size_nofull=on&region_square=on&size_ch=on&size_error_random=on&size_noup=on&size_region=on&size_wc=on&size_wh=on&rot_error_random=on&quality_error_random=on&format_jpg=on&format_error_random=on&baseurl_redirect=on&cors=on&jsonld=on) but every second tests is shown as failed. Could someone verify?

**Comment by glenrobson** [comment]
Thanks for reporting Ill look into it.

**Comment by glenrobson** [comment]
This should now be fixed but let me know if you see any other errors.

(Info in case this reappears) 
It appeared to be a stale Elastic Beanstalk instance which was returning a 404 every second request.  

The direct unproxyed link worked every time:

http://awseb-e-6-awsebloa-1e51vp4xcc2u7-2036344200.us-east-1.elb.amazonaws.com/id_basic?version=3.0&server=iiif.io&prefix=api%2Fimage%2F3.0%2Fexample%2Freference%2F&identifier=67352ccc-d1b0-11e1-89ae-279075081939&t=1571050020450

but proxying it through the iiif site broke every second request:

http://iiif-io.us-east-1.elasticbeanstalk.com/api/image/validator/service/id_squares?version=3.0&server=iiif.io&prefix=api%2Fimage%2F3.0%2Fexample%2Freference%2F&identifier=67352ccc-d1b0-11e1-89ae-279075081939&t=1571052566626

Fixed it by deploying a new version of the iiif.io ElasticBeanstalk application but not sure what caused this initially.
